name: Basic Push Workflow

on: 
  push:
    branch:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Print Hello
        run: echo "Hello from GitHub Actions!"
