name: Branch-Specific Push Workflow

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run Tests
        run: echo "Running tests on push to main or develop"
