name: Testing-cron
on:
  push

jobs:
  nightly:
    name: Akki-test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress nightly tests 🌃
        uses: ./
        with:
          working-directory: examples/basic
